[build]
  command = "cd client && npm install && npm run build"
  publish = "client/dist"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  publish = "client"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[dev.environment]
  VITE_API_URL = "http://localhost:5000/api"

# Environment variables for production
[build.environment]
  VITE_API_URL = "https://your-backend-url.herokuapp.com/api"
